sonar.projectKey=canmakan-web
sonar.organization=canmakan-team
sonar.projectName=canmakan-web
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,node_modules/**,playwright-report/**,test-results/**,coverage/**
