package sg.edu.nus.iss.canmakan.features.dietaryprofile.restrictions

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import sg.edu.nus.iss.canmakan.features.dietaryprofile.restrictions.data.DietaryRestrictionRepository
import sg.edu.nus.iss.canmakan.features.dietaryprofile.restrictions.model.DietaryRestriction
import sg.edu.nus.iss.canmakan.features.dietaryprofile.restrictions.model.DietaryRestrictionSheetUiState
import sg.edu.nus.iss.canmakan.features.family.ActiveProfileManager
import javax.inject.Inject

@HiltViewModel
class DietaryRestrictionViewModel @Inject constructor(
    private val activeProfileManager: ActiveProfileManager,
    private val dietaryRestrictionRepo: DietaryRestrictionRepository,
): ViewModel() {

    // MutableStateFlow always holds a current value and can be updated (hence suitable for UI state)
    // StateFlow is read-only to the UI, so UI can observe, but not change it
    private val _uiState = MutableStateFlow(DietaryRestrictionSheetUiState())
    val uiState: StateFlow<DietaryRestrictionSheetUiState> = _uiState

    init {
        viewModelScope.launch {
            activeProfileManager.currentProfileId.collect { profileId ->
                loadDietaryRestrictionsForProfile(profileId)
            }
        }
    }

    private suspend fun loadDietaryRestrictionsForProfile(profileId: Long) {
        _uiState.value = _uiState.value.copy(isLoading = true)
        val savedDietaryRestrictions = dietaryRestrictionRepo.getDietaryRestrictionsForProfile(profileId)
        _uiState.value = _uiState.value.copy(
            selectedRestrictions = savedDietaryRestrictions,
            isLoading = false
        )
    }

    fun loadDietaryRestrictions() {
        // viewModelScope is a CoroutineScope tied to the lifetime of ViewModel.
        // CoroutineScope defines how long a coroutine is allowed to run
        viewModelScope.launch {
            // .copy() is a function generated by Kotlin for data classes.
            // It creates a new object with the same values as the original, except
            // for the values of the parameters you pass to the function.
            _uiState.value = _uiState.value.copy(isLoading = true)

            val allDietaryRestrictions = dietaryRestrictionRepo.getAllDietaryRestrictions()

            _uiState.value = _uiState.value.copy(
                // "it": refers to unnamed parameter. here it refers to each item in
                // allDietaryRestrictions
                religiousRestrictions = allDietaryRestrictions.filter {it.category == "RELIGIOUS"},
                allergenRestrictions = allDietaryRestrictions.filter {it.category == "ALLERGEN"},
                dietRestrictions = allDietaryRestrictions.filter {it.category == "DIET"},
                isLoading = false
            )
        }
    }
    // This function permits only 1 religious restriction to be selected at any time
    fun selectReligiousRestriction(restrictionId: Long) {
        val currentSelections = _uiState.value.selectedRestrictions.toMutableMap()

        val religiousIds = _uiState.value.religiousRestrictions.map {it.id}
        religiousIds.forEach {id -> currentSelections.remove(id)}

        currentSelections[restrictionId] = "STRICT_AVOID"

        _uiState.value = _uiState.value.copy(selectedRestrictions = currentSelections)
    }
    fun toggleDietaryRestriction(restrictionId: Long) {
        val currentSelections = _uiState.value.selectedRestrictions.toMutableMap()

        if (currentSelections.containsKey(restrictionId)) {
            currentSelections.remove(restrictionId)
        } else {
            currentSelections[restrictionId] = "STRICT_AVOID"
        }

        _uiState.value = _uiState.value.copy(selectedRestrictions = currentSelections)
    }
    
    fun onSave() {
        // because saveDietaryRestrictionSelections ia a suspend fun, it can only be called
        // from inside a coroutine, hence viewModelScope.launch is required
        viewModelScope.launch {
            dietaryRestrictionRepo.saveDietaryRestrictionSelections(
                profileId = activeProfileManager.currentProfileId.value,
                selections = _uiState.value.selectedRestrictions)
        }

    }
}
