package sg.edu.nus.iss.canmakan.dietaryrestriction

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

data class DietaryRestriction(
    val id: Long,
    val code: String,
    val displayName: String,
    val category: String,
    val description: String?
)

data class ProfileRestriction(
    val dietaryProfileId: Long,
    val dietaryRestrictionId: Long,
    val severityLevel: String = "STRICT_AVOID"
)

data class DietaryRestrictionSheetUiState(
    val religiousRestrictions: List<DietaryRestriction> = emptyList(),
    val allergenRestrictions: List<DietaryRestriction> = emptyList(),
    val dietRestrictions: List<DietaryRestriction> = emptyList(),
    // Map is a dictionary with key-value pairs
    val selectedRestrictions: Map<Long, String> = emptyMap(), // key: restriction_id, value: severity_level
    val isLoading: Boolean = false,
    val errorMessage: String? = null

)
@HiltViewModel
class DietaryRestrictionViewModel @Inject constructor(
    private val dietaryRestrictionRepo: DietaryRestrictionRepository,
): ViewModel() {

    // MutableStateFlow always holds a current value and can be updated (hence suitable for UI state)
    // StateFlow is read-only to the UI, so UI can observe, but not change it
    private val _uiState = MutableStateFlow(DietaryRestrictionSheetUiState())
    val uiState: StateFlow<DietaryRestrictionSheetUiState> = _uiState

    fun loadDietaryRestrictions() {
        // viewModelScope is a CoroutineScope tied to the lifetime of ViewModel.
        // CoroutineScope defines how long a coroutine is allowed to run
        viewModelScope.launch {
            // .copy() is a function generated by Kotlin for data classes.
            // It creates a new object with the same values as the original, except
            // for the values of the parameters you pass to the function.
            _uiState.value = _uiState.value.copy(isLoading = true)

            val allDietaryRestrictions = dietaryRestrictionRepo.getAllDietaryRestrictions()

            _uiState.value = _uiState.value.copy(
                // "it": refers to unnamed parameter. here it refers to each item in
                // allDietaryRestrictions
                religiousRestrictions = allDietaryRestrictions.filter {it.category == "RELIGIOUS"},
                allergenRestrictions = allDietaryRestrictions.filter {it.category == "ALLERGEN"},
                dietRestrictions = allDietaryRestrictions.filter {it.category == "DIET"},
                isLoading = false
            )
        }
    }

    fun toggleDietaryRestriction(restrictionId: Long) {
        val currentSelections = _uiState.value.selectedRestrictions.toMutableMap()

        if (currentSelections.containsKey(restrictionId)) {
            currentSelections.remove(restrictionId)
        } else {
            currentSelections[restrictionId] = "STRICT_AVOID"
        }

        _uiState.value = _uiState.value.copy(selectedRestrictions = currentSelections)
    }
}