-- Additive UC5 substitute tags inferred from labels_tags / labels_en.
-- Generated by server/machine-learning/scripts/audit_substitute_tags.py
-- Does not rewrite 01_products.sql INSERT rows.

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten Free sauces'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten Free sauces,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten Free sauces')
END
WHERE barcode = '0008295663900';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten Free sauces'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten Free sauces,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten Free sauces')
END
WHERE barcode = '0051000025494';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten free bread'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten free bread,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten free bread')
END
WHERE barcode = '3760152700667';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten Free sauces'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten Free sauces,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten Free sauces')
END
WHERE barcode = '5060321390391';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten free Breakfast cereals'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten free Breakfast cereals,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten free Breakfast cereals')
END
WHERE barcode = '7750526000895';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'en:gluten-free-flour'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,en:gluten-free-flour,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'en:gluten-free-flour')
END
WHERE barcode = '8881300655204';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten free bread'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten free bread,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten free bread')
END
WHERE barcode = '8887143802515';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten free bread'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten free bread,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten free bread')
END
WHERE barcode = '8887143802539';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten free Breakfast cereals'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten free Breakfast cereals,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten free Breakfast cereals')
END
WHERE barcode = '8887270700159';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten free bread'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten free bread,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten free bread')
END
WHERE barcode = '8888247131129';

-- Remove incorrect breakfast-cereal substitute tag from tahini spread (not a cereal).
UPDATE products
SET category_tags = TRIM(BOTH ',' FROM REPLACE(CONCAT(',', category_tags, ','), ',Gluten free Breakfast cereals,', ','))
WHERE barcode = '8888536703136'
  AND CONCAT(',', category_tags, ',') LIKE '%,Gluten free Breakfast cereals,%';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten Free sauces'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten Free sauces,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten Free sauces')
END
WHERE barcode = '9318939369404';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten Free sauces'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten Free sauces,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten Free sauces')
END
WHERE barcode = '9343317000624';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten Free sauces'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten Free sauces,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten Free sauces')
END
WHERE barcode = '9414732214528';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'ice-creams-and-sorbets'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,ice-creams-and-sorbets,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'ice-creams-and-sorbets')
END
WHERE barcode = '9421904531437';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten free bread'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten free bread,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten free bread')
END
WHERE barcode = '9555243803167';

UPDATE products
SET category_tags = CASE
  WHEN category_tags IS NULL OR TRIM(category_tags) = '' THEN 'Gluten free Breakfast cereals'
  WHEN CONCAT(',', category_tags, ',') LIKE '%,Gluten free Breakfast cereals,%' THEN category_tags
  ELSE CONCAT(category_tags, ',', 'Gluten free Breakfast cereals')
END
WHERE barcode = '9555243803167';
