-- =============================================
-- RECOMMENDATION LOGS (UC5 shown alternatives + UC17 history seed)
-- Regenerated by scripts/generate_recommendation_logs_seed.py
-- Rules: same main_category_en as source; ingredients required; keyword SAFE filter.
-- =============================================
INSERT INTO recommendation_logs (
    id, profile_id, scan_id, source_barcode, recommended_barcode,
    recommended_name, recommended_brand, discovery_tier, verification_tier,
    rank_score, match_reason, data_quality, verdict_at_recommendation,
    shown_to_user, created_at
) VALUES

(1, 1, 2, '0038527591039', '9315090200706', 'Ancient grain flakes', 'Freedom Foods', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 8 DAY + INTERVAL 5 MINUTE),
(2, 1, 3, '9300698500181', '5400601063674', 'Hazelnut sprea', 'Delhaize 365', 'TIER_B_LLM_DISCOVERY', 'TIER_1_RULES', 0.9500, 'llm_suggested_verified', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 6 DAY + INTERVAL 5 MINUTE),
(3, 2, 7, '8850581172007', '9311983909800', 'Cayenne Pepper', 'Whittingtons', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9900, 'prior_safe_scan', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 9 DAY + INTERVAL 5 MINUTE),
(4, 2, 7, '8850581172007', '9313839005087', 'Italian Basil Pesto', 'Sandhurst', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 9 DAY + INTERVAL 6 MINUTE),
(5, 2, 8, '9313839005087', '9311983909800', 'Cayenne Pepper', 'Whittingtons', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9900, 'prior_safe_scan', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 7 DAY + INTERVAL 5 MINUTE),
(6, 2, 8, '9313839005087', '42094722', 'Löwensenf extra scharf 42094722 Senf scharf', 'EDEKA Löwensenf, Löwen, Löwensenf, Senf, famila Löwensenf', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 7 DAY + INTERVAL 6 MINUTE),
(7, 2, 10, '8888077103549', '0888849013999', 'Cheese Crackers Spicy Cheddar', 'Quest', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 0 DAY + INTERVAL 5 MINUTE),
(8, 4, 16, '9317276000032', '5000119120656', 'Set Honey', 'TESCO', 'TIER_B_LLM_DISCOVERY', 'TIER_1_RULES', 0.9500, 'llm_suggested_verified', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 15 DAY + INTERVAL 5 MINUTE),
(9, 4, 16, '9317276000032', '5400601002970', 'Set Honey', 'Delhaize 365', 'TIER_B_LLM_DISCOVERY', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 15 DAY + INTERVAL 6 MINUTE),
(10, 4, 19, '8888383208648', '8885014866550', 'Chef Arifin Tandoori Chicken with Tomato Basmati Rice', '7-Eleven', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 4 DAY + INTERVAL 5 MINUTE),
(11, 5, 21, '4901330300067', '8888030000564', 'Potato Chips Original', 'NTUC Fairprice', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 13 DAY + INTERVAL 5 MINUTE),
(12, 5, 21, '4901330300067', '4901330350109', 'Crispy potato Hot and spicy', 'Calbee', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 13 DAY + INTERVAL 6 MINUTE),
(13, 5, 24, '8850581172007', '8028868001320', 'Peeled Tomatoes in tomato juices', 'Castello Di Battipaglia Fine Foods', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 3 DAY + INTERVAL 5 MINUTE),
(14, 5, 24, '8850581172007', '8888520050253', 'Ground Coriander', 'Crab Brand', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 3 DAY + INTERVAL 6 MINUTE),
(15, 6, 26, '8885014850160', '8888030061541', 'Potato Crisps Smoky B.B.Q', 'NTUC Fairprice', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 11 DAY + INTERVAL 5 MINUTE),
(16, 6, 26, '8885014850160', '0858641003030', 'TDC VEGGIE', 'The Daily Crave', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 11 DAY + INTERVAL 6 MINUTE),
(17, 6, 27, '8888279640019', '8888056832033', 'Purple Wheat Noodles chilli & Lime FLAVOR', 'KOKA', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 9 DAY + INTERVAL 5 MINUTE),
(18, 6, 27, '8888279640019', '9556001129963', '2 Minute Noodles Curry Flavour', 'Maggi, Nestlé', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 9 DAY + INTERVAL 6 MINUTE),
(19, 6, 29, '8885014850160', '8888030061541', 'Potato Crisps Smoky B.B.Q', 'NTUC Fairprice', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 4 DAY + INTERVAL 5 MINUTE),
(20, 6, 29, '8885014850160', '0858641003030', 'TDC VEGGIE', 'The Daily Crave', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 4 DAY + INTERVAL 6 MINUTE),
(21, 7, 33, '8888196305817', '8888196441119', 'Straight Red Tea', 'Pokka', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 7 DAY + INTERVAL 5 MINUTE),
(22, 7, 33, '8888196305817', '8888196184214', 'Pokka Ice Passion Fruit Tea', 'Pokka', 'TIER_A_CATALOG', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 7 DAY + INTERVAL 6 MINUTE),
(23, 7, 35, '9556771000028', '8888082129077', 'NESCAFE 3 IN 1 ORIGINAL', 'NESCAFE', 'TIER_B_LLM_DISCOVERY', 'TIER_1_RULES', 0.9500, 'llm_suggested_verified', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 1 DAY + INTERVAL 5 MINUTE),
(24, 7, 35, '9556771000028', '8888311091991', '3 in 1 Coffee Mix', 'Gold Roast', 'TIER_B_LLM_DISCOVERY', 'TIER_1_RULES', 0.9800, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 1 DAY + INTERVAL 6 MINUTE),
(25, 8, 37, '8854651008845', '8991001780898', 'Twister', 'Delfi', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 9 DAY + INTERVAL 5 MINUTE),
(26, 8, 39, '8888077103549', '0888849013999', 'Cheese Crackers Spicy Cheddar', 'Quest', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 4 DAY + INTERVAL 5 MINUTE),
(27, 9, 43, '8888077102092', '8997025914301', 'Durian Flavour Cream Biscuit', 'Hatari', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 8 DAY + INTERVAL 5 MINUTE),
(28, 9, 44, '9316434288671', '9319133333574', 'Carman Super Berry Muesli Bars cranberry, Blueberry & Goji)', 'Carman', 'TIER_A_CATALOG', 'TIER_1_RULES', 1.0000, 'category_match', 'VERIFIED', 'SAFE', 1, NOW() - INTERVAL 3 DAY + INTERVAL 5 MINUTE);

-- =============================================
-- RECOMMENDATION AI LOGS (Tier B LLM discovery audit seed)
-- =============================================
INSERT INTO recommendation_ai_logs (
    id, scan_id, profile_id, source_barcode, execution_tier,
    model_id, prompt_tokens, completion_tokens, latency_ms,
    llm_candidates_json, candidates_accepted, candidates_rejected, created_at
) VALUES

(1, 3, 1, '9300698500181', 'TIER_B_LLM_DISCOVERY', 'gpt-4o-mini', 380, 95, 1420, '{"candidates":[{"name":"Hazelnut sprea","brand":"Delhaize 365","barcode":"5400601063674"}]}', 1, 0, NOW() - INTERVAL 6 DAY + INTERVAL 4 MINUTE),
(2, 16, 4, '9317276000032', 'TIER_B_LLM_DISCOVERY', 'gpt-4o-mini', 420, 110, 1580, '{"candidates":[{"name":"Set Honey","brand":"TESCO","barcode":"5000119120656"}, {"name":"Set Honey","brand":"Delhaize 365","barcode":"5400601002970"}]}', 1, 1, NOW() - INTERVAL 15 DAY + INTERVAL 4 MINUTE),
(3, 35, 7, '9556771000028', 'TIER_B_LLM_DISCOVERY', 'gpt-4o-mini', 395, 88, 1310, '{"candidates":[{"name":"NESCAFE 3 IN 1 ORIGINAL","brand":"NESCAFE","barcode":"8888082129077"}, {"name":"3 in 1 Coffee Mix","brand":"Gold Roast","barcode":"8888311091991"}]}', 1, 1, NOW() - INTERVAL 1 DAY + INTERVAL 4 MINUTE);
