name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  # 1. ANALYZE CHANGES IN MOBILE, WEB & BACKEND
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      web: ${{ steps.filter.outputs.web }}
      mobile: ${{ steps.filter.outputs.mobile }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'server/backend/**'
            web:
              - 'client/web/**'
            mobile:
              - 'client/mobile/**'

  # 2. BACKEND VERIFICATION & DEPLOYMENT (OMITTED FOR NOW)
  build-backend:
    needs: detect-changes
    # Run if any Backend Files Changed
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    env: 
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_URL: ${{ secrets.MYSQL_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      EAN_SEARCH_API_KEY: ${{ secrets.EAN_SEARCH_API_KEY }}
      SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}   
    steps:
      - uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Build with Maven
        working-directory: server/backend
        run: mvn -B clean package -DskipTests

  # 3. WEB VERIFICATION
  build-web:
    needs: detect-changes
    # Run if any Web Client Files Changed
    if: needs.detect-changes.outputs.web == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: client/web/package-lock.json

      - name: Install web dependencies
        working-directory: client/web
        run: npm ci

      - name: Build web app
        working-directory: client/web
        run: npm run build

  # 4. MOBILE VERIFICATION
  build-mobile:
    needs: detect-changes
    # Run if any Mobile Client Files Changed
    if: needs.detect-changes.outputs.mobile == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Configure Android SDK path
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > client/mobile/local.properties

      - name: Build mobile app
        working-directory: client/mobile
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
